<font size=6>**#1 - Regressão Linear (parte 1)**</font>

---
---

In [5]:
from platform import python_version, platform
from datetime import date

print('Python version:', python_version())
print('Platform:', platform())
print('Date:', date.today())

Python version: 3.10.12
Platform: Linux-6.1.85+-x86_64-with-glibc2.35
Date: 2024-06-29


In [7]:
# importando a biblioteca numérica em Python, ou seja, a NumPy para realizar
# cálculos científicos, análises de dados e matemática em geral
import numpy as np

In [22]:
# variável alvo: renda anual em K
y = np.array([10, 50, 100, 200, 70, 65])

# variável de entrada:
# idade, anos de estudo, sexo (M: 0 | F: 1) e altura (cm), casada (Não:0 | Sim: 1)
X = np.array([
    [31, 7, 1, 1.53, 0],
    [44, 11, 0, 1.62, 0],
    [57, 18, 1, 1.79, 1],
    [65, 12, 0, 1.81, 1],
    [25, 5, 1, 1.65, 0],
    [24, 5, 0, 1.62, 1]
])

In [23]:
# tamanho dos objetos - linhas e colunas
X.shape, y.shape

((6, 5), (6,))

In [24]:
# visualizando o conteúdo do objeto "X"
X

array([[31.  ,  7.  ,  1.  ,  1.53,  0.  ],
       [44.  , 11.  ,  0.  ,  1.62,  0.  ],
       [57.  , 18.  ,  1.  ,  1.79,  1.  ],
       [65.  , 12.  ,  0.  ,  1.81,  1.  ],
       [25.  ,  5.  ,  1.  ,  1.65,  0.  ],
       [24.  ,  5.  ,  0.  ,  1.62,  1.  ]])

In [25]:
# visualizando o conteúdo do objeto "y"
y

array([ 10,  50, 100, 200,  70,  65])

In [27]:
# inserindo uma coluna de "uns" no objeto "X"
X_ = np.c_[np.ones(X.shape[0]), X]

# visualizando o resultado
X_.shape, X_

((6, 6),
 array([[ 1.  , 31.  ,  7.  ,  1.  ,  1.53,  0.  ],
        [ 1.  , 44.  , 11.  ,  0.  ,  1.62,  0.  ],
        [ 1.  , 57.  , 18.  ,  1.  ,  1.79,  1.  ],
        [ 1.  , 65.  , 12.  ,  0.  ,  1.81,  1.  ],
        [ 1.  , 25.  ,  5.  ,  1.  ,  1.65,  0.  ],
        [ 1.  , 24.  ,  5.  ,  0.  ,  1.62,  1.  ]]))

In [18]:
# com a função ".dot" do NumPy, podemos realizar a multiplicação de matrizes
# ou o produto escalar de vetores

# obs: isso somente é possível se ambos os arrays forem matrizes de duas
# dimensões, np.dot realiza a multiplicação matricial entre elas e o resultado
# é uma nova matriz com dimensões (m x n), onde m é o número de linhas da
# primeira matriz e n é o número de colunas da segunda matriz.

matriz_A = np.array([[1, 2], [3, 4]])
matriz_B = np.array([[5, 6], [7, 8]])

print(f'Matriz A (shape): {matriz_A.shape}\n{matriz_A}\n')
print(f'Matriz B (shape): {matriz_B.shape}\n{matriz_B}\n')

matriz_C = np.dot(matriz_A, matriz_B)
print(f'Matriz C (shape): {matriz_C.shape}\n{matriz_C}')

Matriz A (shape): (2, 2)
[[1 2]
 [3 4]]

Matriz B (shape): (2, 2)
[[5 6]
 [7 8]]

Matriz C (shape): (2, 2)
[[19 22]
 [43 50]]


In [21]:
# número de dimensão das matrizes "X" e "X_"
X.ndim, X_.ndim

(2, 2)

In [29]:
# aplicando a multiplicação das matrizes
np.dot(X_.T, X_)

array([[6.00000e+00, 2.46000e+02, 5.80000e+01, 3.00000e+00, 1.00200e+01,
        3.00000e+00],
       [2.46000e+02, 1.15720e+04, 2.75200e+03, 1.13000e+02, 4.18520e+02,
        1.46000e+02],
       [5.80000e+01, 2.75200e+03, 6.88000e+02, 3.00000e+01, 9.88200e+01,
        3.50000e+01],
       [3.00000e+00, 1.13000e+02, 3.00000e+01, 3.00000e+00, 4.97000e+00,
        1.00000e+00],
       [1.00200e+01, 4.18520e+02, 9.88200e+01, 4.97000e+00, 1.67924e+01,
        5.22000e+00],
       [3.00000e+00, 1.46000e+02, 3.50000e+01, 1.00000e+00, 5.22000e+00,
        3.00000e+00]])

In [30]:
# calculando a inversa do resultado da multiplicação das matrizes
np.linalg.inv(np.dot(X_.T, X_))

array([[ 2.01968452e+02,  6.51725251e-01, -4.84083952e-01,
         4.86410887e+00, -1.39306702e+02,  1.27341898e+01],
       [ 6.51725251e-01,  6.16180721e-03, -1.29318458e-02,
         5.10171200e-02, -4.94991304e-01,  4.35508286e-02],
       [-4.84083952e-01, -1.29318458e-02,  4.42970313e-02,
        -1.31626509e-01,  4.14553695e-01, -8.08128432e-02],
       [ 4.86410887e+00,  5.10171200e-02, -1.31626509e-01,
         1.22504926e+00, -3.98265155e+00,  7.10164500e-01],
       [-1.39306702e+02, -4.94991304e-01,  4.14553695e-01,
        -3.98265155e+00,  9.70520423e+01, -8.98318455e+00],
       [ 1.27341898e+01,  4.35508286e-02, -8.08128432e-02,
         7.10164500e-01, -8.98318455e+00,  1.81650600e+00]])

In [31]:
test = np.dot(X_.T, X_)
test

array([[6.00000e+00, 2.46000e+02, 5.80000e+01, 3.00000e+00, 1.00200e+01,
        3.00000e+00],
       [2.46000e+02, 1.15720e+04, 2.75200e+03, 1.13000e+02, 4.18520e+02,
        1.46000e+02],
       [5.80000e+01, 2.75200e+03, 6.88000e+02, 3.00000e+01, 9.88200e+01,
        3.50000e+01],
       [3.00000e+00, 1.13000e+02, 3.00000e+01, 3.00000e+00, 4.97000e+00,
        1.00000e+00],
       [1.00200e+01, 4.18520e+02, 9.88200e+01, 4.97000e+00, 1.67924e+01,
        5.22000e+00],
       [3.00000e+00, 1.46000e+02, 3.50000e+01, 1.00000e+00, 5.22000e+00,
        3.00000e+00]])

In [32]:
np.dot(np.linalg.inv(test), test)

array([[ 1.00000000e+00,  3.43547413e-12,  1.44417811e-12,
         9.59232693e-14,  1.59238104e-14,  8.88178420e-15],
       [ 2.85882429e-15,  1.00000000e+00,  2.43693954e-14,
         1.47798440e-15,  2.10618775e-15,  1.08246745e-15],
       [-1.15185639e-15, -1.67921232e-14,  1.00000000e+00,
        -7.63278329e-16, -3.91684682e-16, -1.80411242e-16],
       [ 1.28785871e-14,  2.05169215e-13,  2.35367281e-14,
         1.00000000e+00, -1.27780591e-15,  3.10862447e-15],
       [-1.63424829e-13, -1.00968123e-11, -2.78177481e-12,
        -1.35003120e-13,  1.00000000e+00, -9.59232693e-14],
       [ 2.42028619e-14,  8.07798273e-13,  1.86739513e-13,
         2.46469511e-14,  2.46051040e-14,  1.00000000e+00]])

In [33]:
np.round(np.dot(np.linalg.inv(test), test))

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [-0., -0.,  1., -0., -0., -0.],
       [ 0.,  0.,  0.,  1., -0.,  0.],
       [-0., -0., -0., -0.,  1., -0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

In [34]:
np.linalg.inv(np.dot(X_.T, X_))

array([[ 2.01968452e+02,  6.51725251e-01, -4.84083952e-01,
         4.86410887e+00, -1.39306702e+02,  1.27341898e+01],
       [ 6.51725251e-01,  6.16180721e-03, -1.29318458e-02,
         5.10171200e-02, -4.94991304e-01,  4.35508286e-02],
       [-4.84083952e-01, -1.29318458e-02,  4.42970313e-02,
        -1.31626509e-01,  4.14553695e-01, -8.08128432e-02],
       [ 4.86410887e+00,  5.10171200e-02, -1.31626509e-01,
         1.22504926e+00, -3.98265155e+00,  7.10164500e-01],
       [-1.39306702e+02, -4.94991304e-01,  4.14553695e-01,
        -3.98265155e+00,  9.70520423e+01, -8.98318455e+00],
       [ 1.27341898e+01,  4.35508286e-02, -8.08128432e-02,
         7.10164500e-01, -8.98318455e+00,  1.81650600e+00]])

In [35]:
np.linalg.inv(X_.T.dot(X_))

array([[ 2.01968452e+02,  6.51725251e-01, -4.84083952e-01,
         4.86410887e+00, -1.39306702e+02,  1.27341898e+01],
       [ 6.51725251e-01,  6.16180721e-03, -1.29318458e-02,
         5.10171200e-02, -4.94991304e-01,  4.35508286e-02],
       [-4.84083952e-01, -1.29318458e-02,  4.42970313e-02,
        -1.31626509e-01,  4.14553695e-01, -8.08128432e-02],
       [ 4.86410887e+00,  5.10171200e-02, -1.31626509e-01,
         1.22504926e+00, -3.98265155e+00,  7.10164500e-01],
       [-1.39306702e+02, -4.94991304e-01,  4.14553695e-01,
        -3.98265155e+00,  9.70520423e+01, -8.98318455e+00],
       [ 1.27341898e+01,  4.35508286e-02, -8.08128432e-02,
         7.10164500e-01, -8.98318455e+00,  1.81650600e+00]])

In [36]:
np.linalg.inv(X_.T.dot(X_)).dot(X_.T).dot(y)

array([-720.91623037,    2.95811518,  -10.7591623 ,   -2.40837696,
        468.58638743,    9.60732984])

In [37]:
beta = np.linalg.inv(X_.T.dot(X_)).dot(X_.T).dot(y)
beta

array([-720.91623037,    2.95811518,  -10.7591623 ,   -2.40837696,
        468.58638743,    9.60732984])

In [38]:
np.round(beta)

array([-721.,    3.,  -11.,   -2.,  469.,   10.])

In [39]:
def fit(X: np.array, y: np.array) -> object:
    """
    Args:
      X: array-like, shape (n_samples, n_features)
      y: array-like, shape (n_samples,)

    Returns:
      intercept: float
      coef: array-like, shape (n_features,)

    Raises:
      ValueError: If X or y are not arrays.
    """
    X_ = np.c_[np.ones(X.shape[0]), X]
    beta = np.linalg.inv(X_.T.dot(X_)).dot(X_.T).dot(y)
    intercept = beta[0]
    coefs = beta[1:]
    return intercept, coefs

In [40]:
alpha, betas = fit(X=X, y=y)

In [41]:
alpha, betas

(-720.9162303664752,
 array([  2.95811518, -10.7591623 ,  -2.40837696, 468.58638743,
          9.60732984]))

In [42]:
np.r_[[alpha], betas]

array([-720.91623037,    2.95811518,  -10.7591623 ,   -2.40837696,
        468.58638743,    9.60732984])

In [43]:
y_hat = X_.dot(np.r_[[alpha], betas])
y_hat

array([ 10.,  50., 100., 200.,  70.,  65.])

In [44]:
y

array([ 10,  50, 100, 200,  70,  65])

In [45]:
X_ = np.c_[np.ones((X.shape[0], 1)), X]

In [46]:
X_

array([[ 1.  , 31.  ,  7.  ,  1.  ,  1.53,  0.  ],
       [ 1.  , 44.  , 11.  ,  0.  ,  1.62,  0.  ],
       [ 1.  , 57.  , 18.  ,  1.  ,  1.79,  1.  ],
       [ 1.  , 65.  , 12.  ,  0.  ,  1.81,  1.  ],
       [ 1.  , 25.  ,  5.  ,  1.  ,  1.65,  0.  ],
       [ 1.  , 24.  ,  5.  ,  0.  ,  1.62,  1.  ]])

In [47]:
X_.dot(np.r_[alpha, betas])

array([ 10.,  50., 100., 200.,  70.,  65.])

In [48]:
def predict(X: np.array, alpha: float, betas: np.array) -> np.array:
    X_ = np.c_[np.ones((X.shape[0], 1)), X]
    return np.round(X_.dot(np.r_[alpha, betas]), 2)

In [49]:
X_new = np.array([[24, 5, 0, 1.62, 1]])
X_new

array([[24.  ,  5.  ,  0.  ,  1.62,  1.  ]])

In [50]:
pred = predict(X=X_new, alpha=alpha, betas=betas)
pred

array([65.])

In [51]:
X_new2 = np.array([[46, 6, 0, 1.69, 1]])
pred2 = predict(X=X_new2, alpha=alpha, betas=betas)
pred2, pred2 / 12

(array([152.12]), array([12.67666667]))

In [52]:
X_new3 = np.array([[46, 12, 1, 1.69, 0]])
pred3 = predict(X=X_new3, alpha=alpha, betas=betas)
pred3, pred3 / 12

(array([75.55]), array([6.29583333]))

In [53]:
X_new4 = np.array([[20, 0, 1, 1.61, 0]])
pred4 = predict(X=X_new4, alpha=alpha, betas=betas)
pred4, pred4 / 12

(array([90.26]), array([7.52166667]))

In [54]:
X_new5 = np.array([[20, 1, 1, 1.61, 0]])
pred5 = predict(X=X_new5, alpha=alpha, betas=betas)
pred5, pred5 / 12

(array([79.5]), array([6.625]))

In [55]:
y_pred6 = predict(X=X, alpha=alpha, betas=betas)
y_pred6

array([ 10.,  50., 100., 200.,  70.,  65.])

In [56]:
%%writefile linear_regression.py
import numpy as np
class MyLinearRegression():
    def __init__(self):
        self.intercept_ = None
        self.coef_ = None

    def fit(self, X: np.array, y: np.array) -> object:
        X_ = np.c_[np.ones((X.shape[0], 1)), X]
        beta = np.linalg.inv(X_.T.dot(X_)).dot(X_.T).dot(y)
        self.intercept_ = beta[0]
        self.coef_ = beta[1:]
        return self

    def predict(self, X: np.array) -> np.array:
        X_ = np.c_[np.ones((X.shape[0], 1)), X]
        return X_.dot(np.r_[self.intercept_, self.coef_])

Writing linear_regression.py


In [57]:
import numpy as np

y = np.array([12, 47, 68, 83, 61, 65, 27, 49, 55, 82])

# variável de entrada:
# idade, anos de estudo, sexo (M: 0 | F: 1) e altura (cm), casada (Não:0 | Sim: 1)

X = np.array([
    [33, 7, 1, 1.53, 0],
    [41, 11, 0, 1.62, 0],
    [55, 18, 1, 1.79, 1],
    [62, 12, 0, 1.81, 1],
    [25, 5, 1, 1.65, 0],
    [24, 5, 0, 1.62, 1],
    [27, 0, 1, 1.61, 0],
    [46, 6, 0, 1.69, 1],
    [33, 4, 0, 1.58, 0],
    [57, 9, 1, 1.88, 0]
])

In [58]:
from linear_regression import MyLinearRegression

In [59]:
model = MyLinearRegression()
model

In [60]:
model.fit(X=X, y=y)
pred = model.predict(X=X)
pred

array([10.05742973, 56.58276866, 67.4505606 , 76.82338566, 56.35395112,
       66.03017742, 32.29030861, 54.69587631, 44.86779195, 83.84774994])

In [61]:
y

array([12, 47, 68, 83, 61, 65, 27, 49, 55, 82])

In [62]:
X_new7 = np.array([[20, 0, 1, 1.61, 0]])
pred_new7 = model.predict(X=X_new7)
pred_new7

array([43.326531])

In [63]:
X_new8 = np.array([[46, 6, 0, 1.69, 1]])
pred_new8 = model.predict(X=X_new8)
pred_new8

array([54.69587631])

In [64]:
model.intercept_, model.coef_

(-398.4363510569897,
 array([ -1.5766032 ,   1.70868309, -24.47763567, 309.17551658,
         -7.10274706]))

In [65]:
%%writefile linear_regression_v2.py
import numpy as np

class MyLinearRegression_v2():
    def __init__(self, learning_rate=0.01, n_iterations=1_000):
        self.intercept_ = None
        self.coef_ = None
        self.learning_rate = learning_rate
        self.n_iterations = n_iterations

    def fit(self, X: np.array, y: np.array) -> object:
        X_ = np.c_[np.ones((X.shape[0], 1)), X]
        self.beta = np.linalg.inv(X_.T.dot(X_)).dot(X_.T).dot(y)
        self.intercept_ = self.beta[0]
        self.coef_ = self.beta [1:]
        return self

    def predict(self, X: np.array) -> np.array:
        X_ = np.c_[np.ones((X.shape[0], 1)), X]
        return X_.dot(np.r_[self.intercept_, self.coef_])

Writing linear_regression_v2.py


In [66]:
from linear_regression_v2 import MyLinearRegression_v2

In [67]:
model = MyLinearRegression_v2()
model

In [68]:
model.fit(X=X, y=y)
pred = model.predict(X=X)
pred

array([10.05742973, 56.58276866, 67.4505606 , 76.82338566, 56.35395112,
       66.03017742, 32.29030861, 54.69587631, 44.86779195, 83.84774994])

In [69]:
y

array([12, 47, 68, 83, 61, 65, 27, 49, 55, 82])

In [70]:
model.intercept_, model.coef_

(-398.4363510569897,
 array([ -1.5766032 ,   1.70868309, -24.47763567, 309.17551658,
         -7.10274706]))

In [71]:
%%writefile linear_regression_v3.py
import numpy as np

class MyLinearRegression_v3():
    def __init__(self, learning_rate=0.01, n_iterations=1_000):
        self.intercept_ = None
        self.coef_ = None
        self.learning_rate = learning_rate
        self.n_iterations = n_iterations

    def fit(self, X: np.array, y: np.array) -> object:
        X_ = np.c_[np.ones((X.shape[0], 1)), X]
        m, n = X_.shape
        self.theta = np.zeros(n)
        for _ in range(self.n_iterations):
            gradients = (2/m) * X_.T.dot(X_.dot(self.theta) - y)
            self.theta -= self.learning_rate * gradients
        self.intercept_ = self.theta[0]
        self.coef_ = self.theta[1:]
        return self

    def predict(self, X: np.array) -> np.array:
        X_ = np.c_[np.ones((X.shape[0], 1)), X]
        return X_.dot(np.r_[self.intercept_, self.coef_])

Writing linear_regression_v3.py


In [72]:
from linear_regression_v3 import MyLinearRegression_v3

In [73]:
model = MyLinearRegression_v3()
model

In [74]:
model.fit(X=X, y=y)
pred = model.predict(X=X)
pred

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [75]:
model.intercept_, model.coef_

(nan, array([nan, nan, nan, nan, nan]))

In [76]:
y = np.array([12, 47, 68, 83, 61, 65, 27, 49, 55, 82])

# variável de entrada:
# idade, anos de estudo, sexo (M: 0 | F: 1) e altura (cm), casada (Não:0 | Sim: 1)
X = np.array([
    [33, 7, 1, 1.53, 0],
    [41, 11, 0, 1.62, 0],
    [55, 18, 1, 1.79, 1],
    [62, 12, 0, 1.81, 1],
    [25, 5, 1, 1.65, 0],
    [24, 5, 0, 1.62, 1],
    [27, 0, 1, 1.61, 0],
    [46, 6, 0, 1.69, 1],
    [33, 4, 0, 1.58, 0],
    [57, 9, 1, 1.88, 0]
])

In [77]:
X_scaled = (X - X.mean(axis=0)) / X.std(axis=0)
X_scaled

array([[-0.54683566, -0.14656673,  1.        , -1.38275492, -0.81649658],
       [ 0.0524363 ,  0.69095744, -1.        , -0.54189044, -0.81649658],
       [ 1.10116221,  2.15662474,  1.        ,  1.04640913,  1.22474487],
       [ 1.62552517,  0.90033848, -1.        ,  1.2332679 ,  1.22474487],
       [-1.14610761, -0.56532881,  1.        , -0.26160228, -0.81649658],
       [-1.2210166 , -0.56532881, -1.        , -0.54189044,  1.22474487],
       [-0.99628962, -1.61223403,  1.        , -0.63531983, -0.81649658],
       [ 0.42698127, -0.35594777, -1.        ,  0.11211526,  1.22474487],
       [-0.54683566, -0.77470986, -1.        , -0.91560799, -0.81649658],
       [ 1.2509802 ,  0.27219535,  1.        ,  1.88727361, -0.81649658]])

In [78]:
model = MyLinearRegression_v3()
model

In [79]:
model.fit(X=X_scaled, y=y)
pred = model.predict(X=X_scaled)
pred

array([13.42550971, 54.99328067, 67.06087603, 78.06297794, 53.53978558,
       63.32228549, 33.84787669, 57.04516864, 44.93601432, 82.76622401])

In [80]:
y

array([12, 47, 68, 83, 61, 65, 27, 49, 55, 82])

In [81]:
model.intercept_, model.coef_

(54.899999907605014,
 array([-16.22143629,   6.00979004, -10.78652807,  29.35362691,
         -2.34083706]))

In [82]:
mean = np.mean(X, axis=0)
std = np.std(X, axis=0)

X_standardized = (X - mean) / std
X_standardized

array([[-0.54683566, -0.14656673,  1.        , -1.38275492, -0.81649658],
       [ 0.0524363 ,  0.69095744, -1.        , -0.54189044, -0.81649658],
       [ 1.10116221,  2.15662474,  1.        ,  1.04640913,  1.22474487],
       [ 1.62552517,  0.90033848, -1.        ,  1.2332679 ,  1.22474487],
       [-1.14610761, -0.56532881,  1.        , -0.26160228, -0.81649658],
       [-1.2210166 , -0.56532881, -1.        , -0.54189044,  1.22474487],
       [-0.99628962, -1.61223403,  1.        , -0.63531983, -0.81649658],
       [ 0.42698127, -0.35594777, -1.        ,  0.11211526,  1.22474487],
       [-0.54683566, -0.77470986, -1.        , -0.91560799, -0.81649658],
       [ 1.2509802 ,  0.27219535,  1.        ,  1.88727361, -0.81649658]])

In [83]:
model = MyLinearRegression_v3()
model

In [84]:
model.fit(X=X_standardized, y=y)
pred = model.predict(X=X_standardized)
pred

array([13.42550971, 54.99328067, 67.06087603, 78.06297794, 53.53978558,
       63.32228549, 33.84787669, 57.04516864, 44.93601432, 82.76622401])

In [85]:
y

array([12, 47, 68, 83, 61, 65, 27, 49, 55, 82])

In [86]:
model.intercept_, model.coef_

(54.899999907605014,
 array([-16.22143629,   6.00979004, -10.78652807,  29.35362691,
         -2.34083706]))

In [87]:
my_data = np.array([[46, 5, 0, 1.68, 1]])
my_data_scaled = (my_data - X.mean(axis=0)) / X.std(axis=0)
my_data_scaled

array([[ 0.42698127, -0.56532881, -1.        ,  0.01868588,  1.22474487]])

In [88]:
salary = model.predict(X=my_data_scaled)
salary, salary / 12

(array([53.04434119]), array([4.42036177]))

In [89]:
my_data2 = np.array([[41, 0, 1, 1.60, 1]])
my_data_scaled2 = (my_data2 - X.mean(axis=0)) / X.std(axis=0)
my_data_scaled2

array([[ 0.0524363 , -1.61223403,  1.        , -0.72874922,  1.22474487]])

In [90]:
salary2 = model.predict(X=my_data_scaled2)
salary2, salary2 / 12

(array([9.31533106]), array([0.77627759]))

In [91]:
my_data3 = np.array([[48, 10, 0, 1.69, 2]])
my_data_scaled3 = (my_data3 - X.mean(axis=0)) / X.std(axis=0)
my_data_scaled3

array([[ 0.57679925,  0.4815764 , -1.        ,  0.11211526,  3.26598632]])

In [92]:
salary3 = model.predict(X=my_data_scaled3)
salary3, salary3 / 12

(array([54.87003647]), array([4.57250304]))

In [93]:
import numpy as np

y = np.array([20410, 47320, 68750, 83155, 61740, 65008,
              27951, 49150, 55044, 82987, 67254, 18741])

# variável de entrada:
# idade, anos de estudo, sexo (M: 0 | F: 1) e altura (cm), casada (Não:0 | Sim: 1), número de filhos
X = np.array([
    [33, 7, 1, 1.53, 0, 1],
    [41, 11, 0, 1.62, 0, 3],
    [55, 18, 1, 1.79, 1, 4],
    [62, 12, 0, 1.81, 1, 3],
    [25, 5, 1, 1.65, 0, 0],
    [24, 5, 0, 1.62, 1, 0],
    [27, 0, 1, 1.61, 0, 1],
    [46, 6, 0, 1.69, 1, 2],
    [33, 4, 0, 1.58, 0, 0],
    [57, 9, 1, 1.88, 0, 4],
    [46, 5, 0, 1.68, 1, 2],
    [41, 0, 1, 1.60, 1, 1]
])

mean = np.mean(X, axis=0)
std = np.std(X, axis=0)

X_standardized = (X - mean) / std
X_standardized

array([[-0.63752627,  0.03415935,  1.        , -1.41568389, -1.        ,
        -0.52758934],
       [ 0.01356439,  0.85398373, -1.        , -0.51630824, -1.        ,
         0.87931557],
       [ 1.15297304,  2.2886764 ,  1.        ,  1.18251243,  1.        ,
         1.58276803],
       [ 1.72267736,  1.05893983, -1.        ,  1.38237368,  1.        ,
         0.87931557],
       [-1.28861692, -0.37575284,  1.        , -0.21651636, -1.        ,
        -1.2310418 ],
       [-1.37000326, -0.37575284, -1.        , -0.51630824,  1.        ,
        -1.2310418 ],
       [-1.12584426, -1.40053332,  1.        , -0.61623887, -1.        ,
        -0.52758934],
       [ 0.42049605, -0.17079675, -1.        ,  0.18320615,  1.        ,
         0.17586311],
       [-0.63752627, -0.58070894, -1.        , -0.91603075, -1.        ,
        -1.2310418 ],
       [ 1.3157457 ,  0.44407154,  1.        ,  2.08188808, -1.        ,
         1.58276803],
       [ 0.42049605, -0.37575284, -1.        ,  0.

In [94]:
model = MyLinearRegression_v3()
model

In [95]:
model.fit(X=X_standardized, y=y)
pred = model.predict(X=X_standardized)
pred, pred/12

(array([20171.42059089, 48123.57889096, 68141.23964692, 85932.26284821,
        59877.23008688, 64700.02717044, 32312.87427055, 59376.75687776,
        53694.16917736, 81213.39101276, 55115.79050924, 18851.25782829]),
 array([1680.95171591, 4010.29824091, 5678.43663724, 7161.02190402,
        4989.76917391, 5391.66893087, 2692.73952255, 4948.06307315,
        4474.51409811, 6767.7825844 , 4592.98254244, 1570.93815236]))

In [96]:
y, y/12

(array([20410, 47320, 68750, 83155, 61740, 65008, 27951, 49150, 55044,
        82987, 67254, 18741]),
 array([1700.83333333, 3943.33333333, 5729.16666667, 6929.58333333,
        5145.        , 5417.33333333, 2329.25      , 4095.83333333,
        4587.        , 6915.58333333, 5604.5       , 1561.75      ]))

In [97]:
%%writefile linear_regression_v4.py
import numpy as np
from abc import ABC, abstractmethod

class BaseLinearModel(ABC):
    @abstractmethod
    def fit(self, X: np.array, y: np.array) -> object:
        pass

    @abstractmethod
    def predict(self, X: np.array) -> np.array:
        pass

class ExactLinearRegression(BaseLinearModel):
    def __init__(self):
        self.intercept_ = None
        self.coef_ = None

    def fit(self, X: np.array, y: np.array) -> object:
        X_ = np.c_[np.ones((X.shape[0], 1)), X]
        self.theta = np.linalg.inv(X_.T.dot(X_)).dot(X_.T).dot(y)
        self.intercept_ = self.theta[0]
        self.coef_ = self.theta[1:]
        return self

    def predict(self, X: np.array) -> np.array:
        X_ = np.c_[np.ones((X.shape[0], 1)), X]
        return X_.dot(np.r_[self.intercept_, self.coef_])

class GDBRegression(BaseLinearModel):
    def __init__(self, learning_rate=0.01, n_iterations=1_000):
        self.intercept_ = None
        self.coef_ = None
        self.learning_rate = learning_rate
        self.n_iterations = n_iterations

    def fit(self, X: np.array, y: np.array) -> object:
        X_ = np.c_[np.ones((X.shape[0], 1)), X]
        m, n = X_.shape
        self.theta = np.zeros(n)
        for _ in range(self.n_iterations):
            gradients = (2/m) * X_.T.dot(X_.dot(self.theta) - y)
            self.theta -= self.learning_rate * gradients
        self.intercept_ = self.theta[0]
        self.coef_ = self.theta[1:]
        return self

    def predict(self, X: np.array) -> np.array:
        X_ = np.c_[np.ones((X.shape[0], 1)), X]
        return X_.dot(np.r_[self.intercept_, self.coef_])

class MyLinearRegression_v4():
    def __init__(self, method='gradient_descent', **kwargs):
        if method == 'exact':
            self.model = ExactLinearRegression(**kwargs)
        elif method == 'gradient_descent':
            self.model = GDBRegression(**kwargs)
        else:
            raise ValueError('Invalid method!. Choose: "exact" or "gradient_descent".')

    def fit(self, X: np.array, y: np.array) -> object:
        self.model.fit(X=X, y=y)
        self.intercept_ = self.model.intercept_
        self.coef_ = self.model.coef_

    def predict(self, X: np.array) -> np.array:
        return self.model.predict(X=X)

Writing linear_regression_v4.py


In [98]:
from linear_regression_v4 import MyLinearRegression_v4

In [99]:
model_exact = MyLinearRegression_v4(method='exact')
model_exact

In [100]:
model_exact.fit(X=X, y=y)
pred = model_exact.predict(X=X)
pred, pred/12

(array([20199.80377363, 47510.23976427, 68129.92193696, 86416.79504591,
        60411.09487125, 64720.92113012, 31892.07948982, 59219.68113174,
        54187.64195849, 81251.14014246, 54875.72096939, 18694.9597858 ]),
 array([1683.31698114, 3959.18664702, 5677.49349475, 7201.39958716,
        5034.25790594, 5393.41009418, 2657.67329082, 4934.97342765,
        4515.63682987, 6770.92834521, 4572.97674745, 1557.91331548]))

In [101]:
y, y/12

(array([20410, 47320, 68750, 83155, 61740, 65008, 27951, 49150, 55044,
        82987, 67254, 18741]),
 array([1700.83333333, 3943.33333333, 5729.16666667, 6929.58333333,
        5145.        , 5417.33333333, 2329.25      , 4095.83333333,
        4587.        , 6915.58333333, 5604.5       , 1561.75      ]))

In [102]:
model_exact.fit(X=X_standardized, y=y)
pred = model_exact.predict(X=X_standardized)
pred, pred/12

(array([20199.80377363, 47510.23976428, 68129.92193697, 86416.79504592,
        60411.09487127, 64720.92113014, 31892.07948983, 59219.68113175,
        54187.6419585 , 81251.14014248, 54875.7209694 , 18694.95978581]),
 array([1683.31698114, 3959.18664702, 5677.49349475, 7201.39958716,
        5034.25790594, 5393.41009418, 2657.67329082, 4934.97342765,
        4515.63682988, 6770.92834521, 4572.97674745, 1557.91331548]))

In [103]:
model_gdb = MyLinearRegression_v4(method='gradient_descent')
model_gdb

In [104]:
model_gdb.fit(X=X, y=y)
pred = model_gdb.predict(X=X)
pred, pred/12

(array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]),
 array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]))

In [105]:
y, y/12

(array([20410, 47320, 68750, 83155, 61740, 65008, 27951, 49150, 55044,
        82987, 67254, 18741]),
 array([1700.83333333, 3943.33333333, 5729.16666667, 6929.58333333,
        5145.        , 5417.33333333, 2329.25      , 4095.83333333,
        4587.        , 6915.58333333, 5604.5       , 1561.75      ]))

In [106]:
model_gdb.fit(X=X_standardized, y=y)
pred = model_gdb.predict(X=X_standardized)
pred, pred/12

(array([20171.42059089, 48123.57889096, 68141.23964692, 85932.26284821,
        59877.23008688, 64700.02717044, 32312.87427055, 59376.75687776,
        53694.16917736, 81213.39101276, 55115.79050924, 18851.25782829]),
 array([1680.95171591, 4010.29824091, 5678.43663724, 7161.02190402,
        4989.76917391, 5391.66893087, 2692.73952255, 4948.06307315,
        4474.51409811, 6767.7825844 , 4592.98254244, 1570.93815236]))

In [107]:
%%writefile linear_regression_v5.py
import numpy as np
from abc import ABC, abstractmethod

class BaseLinearModel(ABC):
    @abstractmethod
    def fit(self, X: np.array, y: np.array) -> object:
        pass

    @abstractmethod
    def predict(self, X: np.array) -> np.array: # Add abstract predict method
        pass

class ExactLinearRegression(BaseLinearModel):
    def __init__(self):
        self.intercept_ = None
        self.coef_ = None

    def fit(self, X: np.array, y: np.array) -> object:
        X_ = np.c_[np.ones((X.shape[0], 1)), X]
        self.theta = np.linalg.inv(X_.T.dot(X_)).dot(X_.T).dot(y)
        self.intercept_ = self.theta[0]
        self.coef_ = self.theta[1:]
        return self

    def predict(self, X: np.array) -> np.array: # Implement predict method
        X_ = np.c_[np.ones((X.shape[0], 1)), X]
        return X_.dot(np.r_[self.intercept_, self.coef_])

class GDBRegression(BaseLinearModel):
    def __init__(self, learning_rate=0.01, n_iterations=1_000):
        self.intercept_ = None
        self.coef_ = None
        self.learning_rate = learning_rate
        self.n_iterations = n_iterations

    def fit(self, X: np.array, y: np.array) -> object:
        X_ = np.c_[np.ones((X.shape[0], 1)), X]
        m, n = X_.shape
        self.theta = np.zeros(n)
        for _ in range(self.n_iterations):
            gradients = (2/m) * X_.T.dot(X_.dot(self.theta) - y)
            self.theta -= self.learning_rate * gradients
        self.intercept_ = self.theta[0]
        self.coef_ = self.theta[1:]
        return self

    def predict(self, X: np.array) -> np.array: # Implement predict method
        X_ = np.c_[np.ones((X.shape[0], 1)), X]
        return X_.dot(np.r_[self.intercept_, self.coef_])

class MyLinearRegression_v5():
    def __init__(self, method='gradient_descent', **kwargs):
        if method == 'exact':
            self.model = ExactLinearRegression(**kwargs)
        elif method == 'gradient_descent':
            self.model = GDBRegression(**kwargs)
        else:
            raise ValueError('Invalid method!. Choose: "exact" or "gradient_descent".')

    def fit(self, X: np.array, y: np.array) -> object:
        self.model.fit(X=X, y=y)
        self.intercept_ = self.model.intercept_
        self.coef_ = self.model.coef_

    def predict(self, X: np.array) -> np.array:
        return self.model.predict(X) # Delegate prediction to the chosen model

Writing linear_regression_v5.py


In [108]:
from linear_regression_v5 import MyLinearRegression_v5

In [109]:
model_exact2 = MyLinearRegression_v5(method='exact')
model_exact2

In [110]:
model_exact2.fit(X=X, y=y)
pred = model_exact2.predict(X=X)
pred, pred/12

(array([20199.80377363, 47510.23976427, 68129.92193696, 86416.79504591,
        60411.09487125, 64720.92113012, 31892.07948982, 59219.68113174,
        54187.64195849, 81251.14014246, 54875.72096939, 18694.9597858 ]),
 array([1683.31698114, 3959.18664702, 5677.49349475, 7201.39958716,
        5034.25790594, 5393.41009418, 2657.67329082, 4934.97342765,
        4515.63682987, 6770.92834521, 4572.97674745, 1557.91331548]))

In [111]:
y, y/12

(array([20410, 47320, 68750, 83155, 61740, 65008, 27951, 49150, 55044,
        82987, 67254, 18741]),
 array([1700.83333333, 3943.33333333, 5729.16666667, 6929.58333333,
        5145.        , 5417.33333333, 2329.25      , 4095.83333333,
        4587.        , 6915.58333333, 5604.5       , 1561.75      ]))

In [112]:
model_exact2.fit(X=X_standardized, y=y)
pred = model_exact2.predict(X=X_standardized)
pred, pred/12

(array([20199.80377363, 47510.23976428, 68129.92193697, 86416.79504592,
        60411.09487127, 64720.92113014, 31892.07948983, 59219.68113175,
        54187.6419585 , 81251.14014248, 54875.7209694 , 18694.95978581]),
 array([1683.31698114, 3959.18664702, 5677.49349475, 7201.39958716,
        5034.25790594, 5393.41009418, 2657.67329082, 4934.97342765,
        4515.63682988, 6770.92834521, 4572.97674745, 1557.91331548]))

In [113]:
model_gdb2 = MyLinearRegression_v5(method='gradient_descent')
model_gdb2

In [114]:
model_gdb2.fit(X=X, y=y)
pred = model_gdb2.predict(X=X)
pred, pred/12

(array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]),
 array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]))

In [115]:
y, y/12

(array([20410, 47320, 68750, 83155, 61740, 65008, 27951, 49150, 55044,
        82987, 67254, 18741]),
 array([1700.83333333, 3943.33333333, 5729.16666667, 6929.58333333,
        5145.        , 5417.33333333, 2329.25      , 4095.83333333,
        4587.        , 6915.58333333, 5604.5       , 1561.75      ]))

In [116]:
model_gdb2.fit(X=X_standardized, y=y)
pred = model_gdb2.predict(X=X_standardized)
pred, pred/12

(array([20171.42059089, 48123.57889096, 68141.23964692, 85932.26284821,
        59877.23008688, 64700.02717044, 32312.87427055, 59376.75687776,
        53694.16917736, 81213.39101276, 55115.79050924, 18851.25782829]),
 array([1680.95171591, 4010.29824091, 5678.43663724, 7161.02190402,
        4989.76917391, 5391.66893087, 2692.73952255, 4948.06307315,
        4474.51409811, 6767.7825844 , 4592.98254244, 1570.93815236]))

In [117]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import (mean_absolute_error,
                             mean_squared_error,
                             r2_score)

In [118]:
y = np.array([20410, 47320, 68750, 83155, 61740, 65008,
              27951, 49150, 55044, 82987, 67254, 18741])

# variável de entrada:
# idade, anos de estudo, sexo (M: 0 | F: 1) e altura (cm), casada (Não:0 | Sim: 1), número de filhos
X = np.array([
    [33, 7, 1, 1.53, 0, 1],
    [41, 11, 0, 1.62, 0, 3],
    [55, 18, 1, 1.79, 1, 4],
    [62, 12, 0, 1.81, 1, 3],
    [25, 5, 1, 1.65, 0, 0],
    [24, 5, 0, 1.62, 1, 0],
    [27, 0, 1, 1.61, 0, 1],
    [46, 6, 0, 1.69, 1, 2],
    [33, 4, 0, 1.58, 0, 0],
    [57, 9, 1, 1.88, 0, 4],
    [46, 5, 0, 1.68, 1, 2],
    [41, 0, 1, 1.60, 1, 1]
])

In [119]:
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.3,
                                                    random_state=42,
                                                    shuffle=True)

In [120]:
lr = LinearRegression()
lr

LinearRegression()

In [121]:
lr.fit(X=X_train, y=y_train)
pred = lr.predict(X=X_test)
pred, pred/12

(array([48033.44239417, 66305.46410413, 31846.34230458, 58982.82034105]),
 array([4002.78686618, 5525.45534201, 2653.86185872, 4915.23502842]))

In [122]:
y_test, y_test/12

(array([67254, 82987, 20410, 55044]),
 array([5604.5       , 6915.58333333, 1700.83333333, 4587.        ]))

In [123]:
lr.intercept_, lr.coef_

(-266209.39318215306,
 array([-2.06293650e+00,  3.00131657e+03, -1.25986485e+04,  1.98262674e+05,
        -6.49285263e+03, -1.36286455e+04]))

In [124]:
lr.score(X=X_train, y=y_train)

0.9920149949379475

In [125]:
lr.fit(X=X_train, y=y_train)

pred_train = lr.predict(X=X_train)
pred_test = lr.predict(X=X_test)

<font size=5>**Métricas para avaliar o seu modelo de regressão: dominando a arte da previsão**</font>

No mundo da inteligência artificial, os modelos de regressão reinam como reis da previsão de valores contínuos. Mas, como saber se o seu modelo está realmente mandando bem? É aí que entram as métricas de avaliação!

Para análise preditiva, conhecer as métricas certas é fundamental para:

* **Desvendar a precisão do seu modelo:** descobrir o quão perto as suas previsões estão da realidade.
* **Identificar áreas para aprimoramento:** entender onde o seu modelo precisa de ajustes para se tornar ainda mais preciso.
* **Escolher o melhor modelo para o seu problema:** comparar diferentes modelos e escolher o que melhor se encaixa nas suas necessidades.

As principais métricas de avaliação de modelos de regressão:

**1. Erro Médio Absoluto (MAE):** a soma da distância absoluta entre os valores previstos e os valores reais. Quanto menor o MAE, melhor o modelo. Imagine um amigo que sempre te dá um presente, mas nem sempre acerta o que você queria. O MAE seria a média da diferença de valor entre os presentes e o que você realmente desejava.

**2. Erro Quadrático Médio (MSE):** a média dos quadrados da distância entre os valores previstos e os valores reais. Ele penaliza mais erros maiores, dando mais peso a eles. É como ter um amigo que te dá presentes caros, mas nem sempre acerta o que você queria. O MSE seria a média do quadrado da diferença de valor entre os presentes e o que você realmente desejava, dando mais peso aos presentes mais caros.

**3. Raiz Quadrada do Erro Quadrático Médio (RMSE):** a raiz quadrada do MSE. É útil para ter uma ideia da magnitude do erro em unidades da variável original. Imagine ter um amigo que te dá presentes, mas nem sempre acerta o que você queria, e você calcula a diferença de valor entre os presentes e o que você realmente desejava. O RMSE seria a média da raiz quadrada dessa diferença de valor, te dando uma ideia do erro em reais, por exemplo.

**4. Coeficiente de Determinação (R²):** indica a porcentagem da variabilidade da variável alvo explicada pelo modelo. Um R² alto significa que o modelo explica bem a variabilidade dos dados, enquanto um R² baixo significa que o modelo explica mal essa variabilidade. Imagine ter um amigo que te conhece muito bem e consegue prever o que você vai querer de presente. O R² seria a porcentagem das vezes que ele acerta o presente que você queria.

**5. Erro Percentual Absoluto Médio (MAPE):** o erro médio absoluto dividido pela média dos valores reais, expresso em porcentagem. É útil quando se trabalha com valores que possuem grande magnitude. Imagine ter um amigo rico que te dá presentes, mas nem sempre acerta o que você queria. O MAPE seria a média da diferença de valor entre os presentes e o que você realmente desejava, dividida pela média do valor dos presentes, te dando uma ideia do erro em porcentagem.

**Outras métricas importantes:**

* **Índice de Concordância de Lin's:** mede a concordância entre a ordem de classificação dos valores previstos e os valores reais.
* **Erro Mediano Absoluto (MAD):** a mediana da distância absoluta entre os valores previstos e os valores reais.
* **Escala de Brier:** mede a probabilidade de erro do modelo em previsões binárias.

**Lembre-se:**

* A escolha da métrica ideal depende do seu problema específico e dos seus objetivos.
* É importante analisar várias métricas juntas para ter uma visão completa do desempenho do seu modelo.
* Não existe uma métrica única que seja perfeita para todos os casos.

Com essas dicas e as métricas em mãos, você estará pronto para desvendar os segredos da avaliação de modelos de regressão e construir modelos de previsão cada vez mais precisos e confiáveis!

In [126]:
mae_train = mean_absolute_error(y_true=y_train, y_pred=pred_train)
mae_test = mean_absolute_error(y_true=y_test, y_pred=pred_test)

mse_train = mean_squared_error(y_true=y_train, y_pred=pred_train)
mse_test = mean_squared_error(y_true=y_test, y_pred=pred_test)

rmse_train = mean_squared_error(y_true=y_train, y_pred=pred_train, squared=False)
rmse_test = mean_squared_error(y_true=y_test, y_pred=pred_test, squared=False)

mape_train = np.mean(np.abs((y_train - pred_train) / y_train))
mape_test = np.mean(np.abs((y_test - pred_test) / y_test))

r2_train = r2_score(y_true=y_train, y_pred=pred_train)
r2_test = r2_score(y_true=y_test, y_pred=pred_test)

In [127]:
data = {
    'dataset': ['train', 'test'],
    'mae': [mae_train, mae_test],
    'mse': [mse_train, mse_test],
    'rmse': [rmse_train, rmse_test],
    'mape': [mape_train, mape_test],
    'r2': [r2_train, r2_test]
}

df_metrics = pd.DataFrame(data=data)
# df_metrics.reset_index(drop=True, inplace=True)
df_metrics

dataset           mae           mse          rmse      mape        r2
0   train   1410.677648  3.219540e+06   1794.307627  0.029309  0.992015
1    test  12819.314037  1.985019e+08  14089.071168  0.279673  0.625785

In [128]:
scal = StandardScaler()
X_train_scaled = scal.fit_transform(X_train)
X_test_scaled = scal.transform(X_test)

In [129]:
lr.fit(X=X_train_scaled, y=y_train)
pred = lr.predict(X=X_test_scaled)
pred, pred/12

(array([48033.44239417, 66305.46410413, 31846.34230458, 58982.82034105]),
 array([4002.78686618, 5525.45534201, 2653.86185872, 4915.23502842]))

In [130]:
y_test, y_test/12

(array([67254, 82987, 20410, 55044]),
 array([5604.5       , 6915.58333333, 1700.83333333, 4587.        ]))

In [131]:
lr.intercept_, lr.coef_

(52726.87500000001,
 array([   -27.25961006,  17399.71058407,  -6299.32427388,  15387.32626336,
         -3143.33876379, -18970.27172694]))

In [132]:
lr.score(X=X_train_scaled, y=y_train)

0.9920149949379475

In [133]:
lr.fit(X=X_train_scaled, y=y_train)

pred_train = lr.predict(X=X_train_scaled)
pred_test = lr.predict(X=X_test_scaled)

In [134]:
mae_train = mean_absolute_error(y_true=y_train, y_pred=pred_train)
mae_test = mean_absolute_error(y_true=y_test, y_pred=pred_test)

mse_train = mean_squared_error(y_true=y_train, y_pred=pred_train)
mse_test = mean_squared_error(y_true=y_test, y_pred=pred_test)

rmse_train = mean_squared_error(y_true=y_train, y_pred=pred_train, squared=False)
rmse_test = mean_squared_error(y_true=y_test, y_pred=pred_test, squared=False)

mape_train = np.mean(np.abs((y_train - pred_train) / y_train))
mape_test = np.mean(np.abs((y_test - pred_test) / y_test))

r2_train = r2_score(y_true=y_train, y_pred=pred_train)
r2_test = r2_score(y_true=y_test, y_pred=pred_test)

In [135]:
data = {
    'dataset': ['train', 'test'],
    'mae': [mae_train, mae_test],
    'mse': [mse_train, mse_test],
    'rmse': [rmse_train, rmse_test],
    'mape': [mape_train, mape_test],
    'r2': [r2_train, r2_test]
}

df_metrics = pd.DataFrame(data=data)
# df_metrics.reset_index(drop=True, inplace=True)
df_metrics

dataset           mae           mse          rmse      mape        r2
0   train   1410.677648  3.219540e+06   1794.307627  0.029309  0.992015
1    test  12819.314037  1.985019e+08  14089.071168  0.279673  0.625785

In [136]:
%%writefile linear_regression_v6.py
import numpy as np
from abc import ABC, abstractmethod

class BaseLinearModel(ABC):
    @abstractmethod
    def fit(self, X: np.array, y: np.array) -> object:
        pass

    @abstractmethod
    def predict(self, X: np.array) -> np.array: # Add abstract predict method
        pass

class ExactLinearRegression(BaseLinearModel):
    def __init__(self):
        self.intercept_ = None
        self.coef_ = None

    def fit(self, X: np.array, y: np.array) -> object:
        X_ = np.c_[np.ones((X.shape[0], 1)), X]
        self.theta = np.linalg.inv(X_.T.dot(X_)).dot(X_.T).dot(y)
        self.intercept_ = self.theta[0]
        self.coef_ = self.theta[1:]
        return self

    def predict(self, X: np.array) -> np.array: # Implement predict method
        X_ = np.c_[np.ones((X.shape[0], 1)), X]
        return X_.dot(np.r_[self.intercept_, self.coef_])

class GDBRegression(BaseLinearModel):
    def __init__(self, learning_rate=0.01, n_iterations=1_000):
        self.intercept_ = None
        self.coef_ = None
        self.learning_rate = learning_rate
        self.n_iterations = n_iterations

    def fit(self, X: np.array, y: np.array) -> object:
        X_ = np.c_[np.ones((X.shape[0], 1)), X]
        m, n = X_.shape
        self.theta = np.zeros(n)
        for _ in range(self.n_iterations):
            gradients = (2/m) * X_.T.dot(X_.dot(self.theta) - y)
            self.theta -= self.learning_rate * gradients
        self.intercept_ = self.theta[0]
        self.coef_ = self.theta[1:]
        return self

    def predict(self, X: np.array) -> np.array: # Implement predict method
        X_ = np.c_[np.ones((X.shape[0], 1)), X]
        return X_.dot(np.r_[self.intercept_, self.coef_])

class RidgeRegression(BaseLinearModel):
    def __init__(self, lambda_rate=1, learning_rate=0.01, n_iterations=1_000):
        self.intercept_ = None
        self.coef_ = None
        self.lambda_rate = lambda_rate
        self.learning_rate = learning_rate
        self.n_iterations = n_iterations

    def fit(self, X: np.array, y: np.array) -> object:
        X_ = np.c_[np.ones((X.shape[0], 1)), X]
        m, n = X_.shape
        self.theta = np.zeros(n)
        for _ in range(self.n_iterations):
            gradients = (2/m) * X_.T.dot(X_.dot(self.theta) - y) + (2 * self.lambda_rate/m) * self.theta
            gradients -= (2 * self.lambda_rate/m) * self.theta[0]
            self.theta -= self.learning_rate * gradients
        self.intercept_ = self.theta[0]
        self.coef_ = self.theta[1:]
        return self

    def predict(self, X: np.array) -> np.array:
        X_ = np.c_[np.ones((X.shape[0], 1)), X]
        return X_.dot(np.r_[self.intercept_, self.coef_])

class MyLinearRegression_v6():
    def __init__(self, method='gradient_descent', **kwargs):
        if method == 'exact':
            self.model = ExactLinearRegression(**kwargs)
        elif method == 'gradient_descent':
            self.model = GDBRegression(**kwargs)
        elif method == 'ridge':
            self.model = RidgeRegression(**kwargs)
        else:
            raise ValueError('Invalid method!. Choose between methods: "exact", "gradient_descent", or "ridge".')

    def fit(self, X: np.array, y: np.array) -> object:
        self.model.fit(X=X, y=y)
        self.intercept_ = self.model.intercept_
        self.coef_ = self.model.coef_

    def predict(self, X: np.array) -> np.array:
        return self.model.predict(X) # Delegate prediction to the chosen model

Writing linear_regression_v6.py


In [137]:
import numpy as np

y = np.array([20410, 47320, 68750, 83155, 61740, 65008,
              27951, 49150, 55044, 82987, 67254, 18741])

# variável de entrada:
# idade, anos de estudo, sexo (M: 0 | F: 1) e altura (cm), casada (Não:0 | Sim: 1), número de filhos
X = np.array([
    [33, 7, 1, 1.53, 0, 1],
    [41, 11, 0, 1.62, 0, 3],
    [55, 18, 1, 1.79, 1, 4],
    [62, 12, 0, 1.81, 1, 3],
    [25, 5, 1, 1.65, 0, 0],
    [24, 5, 0, 1.62, 1, 0],
    [27, 0, 1, 1.61, 0, 1],
    [46, 6, 0, 1.69, 1, 2],
    [33, 4, 0, 1.58, 0, 0],
    [57, 9, 1, 1.88, 0, 4],
    [46, 5, 0, 1.68, 1, 2],
    [41, 0, 1, 1.60, 1, 1]
])

In [138]:
from linear_regression_v6 import MyLinearRegression_v6

In [139]:
model_exact3 = MyLinearRegression_v6(method='exact')
model_exact3

In [140]:
model_exact3.fit(X=X, y=y)
pred = model_exact3.predict(X=X)
pred, pred/12

(array([20199.80377363, 47510.23976427, 68129.92193696, 86416.79504591,
        60411.09487125, 64720.92113012, 31892.07948982, 59219.68113174,
        54187.64195849, 81251.14014246, 54875.72096939, 18694.9597858 ]),
 array([1683.31698114, 3959.18664702, 5677.49349475, 7201.39958716,
        5034.25790594, 5393.41009418, 2657.67329082, 4934.97342765,
        4515.63682987, 6770.92834521, 4572.97674745, 1557.91331548]))

In [141]:
y, y/12

(array([20410, 47320, 68750, 83155, 61740, 65008, 27951, 49150, 55044,
        82987, 67254, 18741]),
 array([1700.83333333, 3943.33333333, 5729.16666667, 6929.58333333,
        5145.        , 5417.33333333, 2329.25      , 4095.83333333,
        4587.        , 6915.58333333, 5604.5       , 1561.75      ]))

In [142]:
mean = np.mean(X, axis=0)
std = np.std(X, axis=0)

X_standardized = (X - mean) / std
X_standardized

array([[-0.63752627,  0.03415935,  1.        , -1.41568389, -1.        ,
        -0.52758934],
       [ 0.01356439,  0.85398373, -1.        , -0.51630824, -1.        ,
         0.87931557],
       [ 1.15297304,  2.2886764 ,  1.        ,  1.18251243,  1.        ,
         1.58276803],
       [ 1.72267736,  1.05893983, -1.        ,  1.38237368,  1.        ,
         0.87931557],
       [-1.28861692, -0.37575284,  1.        , -0.21651636, -1.        ,
        -1.2310418 ],
       [-1.37000326, -0.37575284, -1.        , -0.51630824,  1.        ,
        -1.2310418 ],
       [-1.12584426, -1.40053332,  1.        , -0.61623887, -1.        ,
        -0.52758934],
       [ 0.42049605, -0.17079675, -1.        ,  0.18320615,  1.        ,
         0.17586311],
       [-0.63752627, -0.58070894, -1.        , -0.91603075, -1.        ,
        -1.2310418 ],
       [ 1.3157457 ,  0.44407154,  1.        ,  2.08188808, -1.        ,
         1.58276803],
       [ 0.42049605, -0.37575284, -1.        ,  0.

In [143]:
model_exact3.fit(X=X_standardized, y=y)
pred = model_exact3.predict(X=X_standardized)
pred, pred/12

(array([20199.80377363, 47510.23976428, 68129.92193697, 86416.79504592,
        60411.09487127, 64720.92113014, 31892.07948983, 59219.68113175,
        54187.6419585 , 81251.14014248, 54875.7209694 , 18694.95978581]),
 array([1683.31698114, 3959.18664702, 5677.49349475, 7201.39958716,
        5034.25790594, 5393.41009418, 2657.67329082, 4934.97342765,
        4515.63682988, 6770.92834521, 4572.97674745, 1557.91331548]))

In [144]:
y, y/12

(array([20410, 47320, 68750, 83155, 61740, 65008, 27951, 49150, 55044,
        82987, 67254, 18741]),
 array([1700.83333333, 3943.33333333, 5729.16666667, 6929.58333333,
        5145.        , 5417.33333333, 2329.25      , 4095.83333333,
        4587.        , 6915.58333333, 5604.5       , 1561.75      ]))

In [145]:
model_gdb3 = MyLinearRegression_v6(method='gradient_descent')
model_gdb3

In [146]:
model_gdb3.fit(X=X, y=y)
pred = model_gdb3.predict(X=X)
pred, pred/12

(array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]),
 array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]))

In [147]:
model_gdb3.fit(X=X_standardized, y=y)
pred = model_gdb3.predict(X=X_standardized)
pred, pred/12

(array([20171.42059089, 48123.57889096, 68141.23964692, 85932.26284821,
        59877.23008688, 64700.02717044, 32312.87427055, 59376.75687776,
        53694.16917736, 81213.39101276, 55115.79050924, 18851.25782829]),
 array([1680.95171591, 4010.29824091, 5678.43663724, 7161.02190402,
        4989.76917391, 5391.66893087, 2692.73952255, 4948.06307315,
        4474.51409811, 6767.7825844 , 4592.98254244, 1570.93815236]))

In [148]:
y, y/12

(array([20410, 47320, 68750, 83155, 61740, 65008, 27951, 49150, 55044,
        82987, 67254, 18741]),
 array([1700.83333333, 3943.33333333, 5729.16666667, 6929.58333333,
        5145.        , 5417.33333333, 2329.25      , 4095.83333333,
        4587.        , 6915.58333333, 5604.5       , 1561.75      ]))

In [149]:
model_ridge3 = MyLinearRegression_v6(method='ridge')
model_ridge3

In [150]:
model_ridge3.fit(X=X, y=y)
pred = model_ridge3.predict(X=X)
pred, pred/12

(array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]),
 array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]))

In [151]:
model_ridge3.fit(X=X_standardized, y=y)
pred = model_ridge3.predict(X=X_standardized)
pred, pred/12

(array([25387.95220109, 43543.87286838, 88014.93107194, 87187.10388496,
        52402.57389149, 56620.11334691, 29344.96056743, 58967.82294867,
        37843.26868722, 81668.66533698, 54989.7413043 , 31538.99280089]),
 array([2115.66268342, 3628.65607236, 7334.57758933, 7265.59199041,
        4366.88115762, 4718.34277891, 2445.41338062, 4913.98524572,
        3153.60572394, 6805.72211141, 4582.47844203, 2628.24940007]))

In [152]:
y, y/12

(array([20410, 47320, 68750, 83155, 61740, 65008, 27951, 49150, 55044,
        82987, 67254, 18741]),
 array([1700.83333333, 3943.33333333, 5729.16666667, 6929.58333333,
        5145.        , 5417.33333333, 2329.25      , 4095.83333333,
        4587.        , 6915.58333333, 5604.5       , 1561.75      ]))

In [153]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.linear_model import (LinearRegression,
                                  Ridge,
                                  Lasso,
                                  ElasticNet,
                                  SGDRegressor,
                                  BayesianRidge,
                                  HuberRegressor,
                                  RANSACRegressor)
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (mean_absolute_error,
                             mean_squared_error,
                             r2_score)

In [154]:
data = load_diabetes()
data.keys()

dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename', 'data_module'])

In [155]:
print(data.DESCR)

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

  :Number of Instances: 442

  :Number of Attributes: First 10 columns are numeric predictive values

  :Target: Column 11 is a quantitative measure of disease progression one year after baseline

  :Attribute Information:
      - age     age in years
      - sex
      - bmi     body mass index
      - bp      average blood pressure
      - s1      tc, total serum cholesterol
      - s2      ldl, low-density lipoproteins
      - s3      hdl, high-density lipoproteins
      - s4      tch, total cholesterol / HDL
      - s5      ltg, possibly log of serum triglycerides level
      - s6      glu, blood sugar level

Note: Each of these 1

In [156]:
df = pd.DataFrame(data=data.data, columns=data.feature_names)
df['target'] = data.target
df.head()

age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  target  
0 -0.002592  0.019907 -0.017646   151.0  
1 -0.039493 -0.068332 -0.092204    75.0  
2 -0.002592  0.002861 -0.025930   141.0  
3  0.034309  0.022688 -0.009362   206.0  
4 -0.002592 -0.031988 -0.046641   135.0

In [157]:
X, y = data.data, data.target

In [158]:
X[:5]

array([[ 0.03807591,  0.05068012,  0.06169621,  0.02187239, -0.0442235 ,
        -0.03482076, -0.04340085, -0.00259226,  0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, -0.02632753, -0.00844872,
        -0.01916334,  0.07441156, -0.03949338, -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, -0.00567042, -0.04559945,
        -0.03419447, -0.03235593, -0.00259226,  0.00286131, -0.02593034],
       [-0.08906294, -0.04464164, -0.01159501, -0.03665608,  0.01219057,
         0.02499059, -0.03603757,  0.03430886,  0.02268774, -0.00936191],
       [ 0.00538306, -0.04464164, -0.03638469,  0.02187239,  0.00393485,
         0.01559614,  0.00814208, -0.00259226, -0.03198764, -0.04664087]])

In [159]:
y[:5]

array([151.,  75., 141., 206., 135.])

In [160]:
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.3,
                                                    random_state=42,
                                                    shuffle=True)

In [161]:
lr_model = LinearRegression()
lr_model

LinearRegression()

In [162]:
lr_model.fit(X=X_train, y=y_train)
pred_lr = lr_model.predict(X=X_test)
pred_lr[:10]

array([138.46970031, 181.10052342, 125.34400904, 292.75977277,
       123.8830531 ,  91.89830434, 257.26463123, 177.76169318,
        84.98549706, 109.15960992])

In [163]:
y_test[:10]

array([219.,  70., 202., 230., 111.,  84., 242., 272.,  94.,  96.])

In [164]:
lr_model.fit(X=X_train, y=y_train)

pred_train = lr_model.predict(X=X_train)
pred_test = lr_model.predict(X=X_test)

In [165]:
mae_train = mean_absolute_error(y_true=y_train, y_pred=pred_train)
mae_test = mean_absolute_error(y_true=y_test, y_pred=pred_test)

mse_train = mean_squared_error(y_true=y_train, y_pred=pred_train)
mse_test = mean_squared_error(y_true=y_test, y_pred=pred_test)

rmse_train = mean_squared_error(y_true=y_train, y_pred=pred_train, squared=False)
rmse_test = mean_squared_error(y_true=y_test, y_pred=pred_test, squared=False)

mape_train = np.mean(np.abs((y_train - pred_train) / y_train))
mape_test = np.mean(np.abs((y_test - pred_test) / y_test))

r2_train = r2_score(y_true=y_train, y_pred=pred_train)
r2_test = r2_score(y_true=y_test, y_pred=pred_test)

In [166]:
data = {
    'dataset': ['train', 'test'],
    'mae': [mae_train, mae_test],
    'mse': [mse_train, mse_test],
    'rmse': [rmse_train, rmse_test],
    'mape': [mape_train, mape_test],
    'r2': [r2_train, r2_test]
}

df_metrics = pd.DataFrame(data=data)
# df_metrics.reset_index(drop=True, inplace=True)
df_metrics

dataset        mae          mse       rmse      mape        r2
0   train  44.097835  2924.046379  54.074452  0.395925  0.524412
1    test  41.919378  2821.750981  53.120156  0.366720  0.477290

In [167]:
def train_test_model(model, X_train, X_test, y_train, y_test):
    model.fit(X=X_train, y=y_train)
    pred_train = model.predict(X=X_train)
    pred_test = model.predict(X=X_test)

    mae_train = mean_absolute_error(y_true=y_train, y_pred=pred_train)
    mae_test = mean_absolute_error(y_true=y_test, y_pred=pred_test)

    mse_train = mean_squared_error(y_true=y_train, y_pred=pred_train)
    mse_test = mean_squared_error(y_true=y_test, y_pred=pred_test)

    rmse_train = mean_squared_error(y_true=y_train, y_pred=pred_train, squared=False)
    rmse_test = mean_squared_error(y_true=y_test, y_pred=pred_test, squared=False)

    mape_train = np.mean(np.abs((y_train - pred_train) / y_train))
    mape_test = np.mean(np.abs((y_test - pred_test) / y_test))

    r2_train = r2_score(y_true=y_train, y_pred=pred_train)
    r2_test = r2_score(y_true=y_test, y_pred=pred_test)

    data = {
        'dataset': ['train', 'test'],
        'mae': [mae_train, mae_test],
        'mse': [mse_train, mse_test],
        'rmse': [rmse_train, rmse_test],
        'mape': [mape_train, mape_test],
        'r2': [r2_train, r2_test]
    }

    df_metrics = pd.DataFrame(data=data)
    return df_metrics

In [168]:
lr = LinearRegression()
lr

LinearRegression()

In [169]:
lr_model = train_test_model(model=lr,
                           X_train=X_train,
                           X_test=X_test,
                           y_train=y_train,
                           y_test=y_test)

lr_model

dataset        mae          mse       rmse      mape        r2
0   train  44.097835  2924.046379  54.074452  0.395925  0.524412
1    test  41.919378  2821.750981  53.120156  0.366720  0.477290

In [170]:
ridge = Ridge(alpha=0.1)
ridge

Ridge(alpha=0.1)

In [171]:
ridge_model = train_test_model(model=ridge,
                               X_train=X_train,
                               X_test=X_test,
                               y_train=y_train,
                               y_test=y_test)

ridge_model

dataset        mae          mse       rmse      mape        r2
0   train  44.800368  2971.777880  54.514015  0.404545  0.516649
1    test  41.851157  2805.401298  52.966039  0.365514  0.480318

In [172]:
lasso = Lasso(alpha=0.1)
lasso

Lasso(alpha=0.1)

In [173]:
lasso_model = train_test_model(model=lasso,
                               X_train=X_train,
                               X_test=X_test,
                               y_train=y_train,
                               y_test=y_test)

lasso_model

dataset        mae          mse       rmse      mape        r2
0   train  44.968131  2991.667799  54.696141  0.405333  0.513414
1    test  41.938631  2775.165076  52.679836  0.366491  0.485919

In [174]:
elastic_net = ElasticNet(alpha=0.1)
elastic_net

ElasticNet(alpha=0.1)

In [175]:
elastic_net_model = train_test_model(model=elastic_net,
                                   X_train=X_train,
                                   X_test=X_test,
                                   y_train=y_train,
                                   y_test=y_test)

elastic_net_model

dataset        mae          mse       rmse      mape        r2
0   train  63.487948  5516.806817  74.275210  0.604798  0.102708
1    test  60.235210  4836.358800  69.543934  0.570864  0.104097

In [176]:
sgd = SGDRegressor(alpha=0.1)
sgd

SGDRegressor(alpha=0.1)

In [177]:
sgd_model = train_test_model(model=sgd,
                            X_train=X_train,
                            X_test=X_test,
                            y_train=y_train,
                            y_test=y_test)

sgd_model

dataset        mae          mse       rmse      mape        r2
0   train  64.900056  5790.433948  76.094901  0.618851  0.058203
1    test  62.019916  5092.378414  71.360903  0.588611  0.056671

In [178]:
bayesian_ridge = BayesianRidge()
bayesian_ridge

BayesianRidge()

In [179]:
bayesian_ridge_model = train_test_model(model=bayesian_ridge,
                                        X_train=X_train,
                                        X_test= X_test,
                                        y_train=y_train,
                                        y_test=y_test)

bayesian_ridge_model

dataset        mae          mse       rmse      mape        r2
0   train  44.394935  2947.597286  54.291779  0.399487  0.520582
1    test  41.850972  2815.042614  53.056975  0.364277  0.478532

In [180]:
huber = HuberRegressor()
huber

HuberRegressor()

In [181]:
huber_model = train_test_model(model=huber,
                               X_train=X_train,
                               X_test= X_test,
                               y_train=y_train,
                               y_test=y_test)

huber_model

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_huber.py:342: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


dataset        mae          mse       rmse      mape        r2
0   train  43.938556  2942.034949  54.240529  0.391384  0.521487
1    test  41.891437  2823.712589  53.138617  0.362938  0.476926

In [182]:
ransac = RANSACRegressor()
ransac

RANSACRegressor()

In [183]:
ransac_model = train_test_model(model=ransac,
                               X_train=X_train,
                               X_test= X_test,
                               y_train=y_train,
                               y_test=y_test)

ransac_model

dataset        mae          mse       rmse      mape        r2
0   train  51.948567  4313.311867  65.675809  0.464905  0.298452
1    test  53.403414  4504.729296  67.117280  0.468419  0.165529